name: Lint Check

on: 
  pull_request:
    branches:
      - master  # or the branch you want to protect

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # specify your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Run lint
      run: npm run lint
